---
# tasks file for setup-postgres
- name: Create dir
  file:
    path: "{{ dir }}"
    state: directory

- name: Copy compose.yaml
  copy:
    src: docker-compose_postgres.yaml
    dest: "{{ dir }}/compose.yaml"

- name: Copy envs
  copy:
    src: container.env
    dest: "{{ dir }}/.env"

- name: Run backend database
  command: docker compose -f {{ dir }}/compose.yaml up -d --build --force-recreate

- name: Create table
  command: docker compose -f {{ dir }}/compose.yaml exec -T db bash -c 'psql -U $POSTGRES_USER -d $POSTGRES_DB -c "CREATE TABLE book (id SERIAL PRIMARY KEY, title VARCHAR(100) NOT NULL, author VARCHAR(100) NOT NULL, price FLOAT NOT NULL);"'