services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app/__init__.py
      FLASK_RUN_HOST: 0.0.0.0
      DATABASE_URL: "${DB_URL}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s